### ISSUE TITLE
Wrapper support

### ISSUE THREAD

**Issue by ponchorage** [theonion/videojs-vast-plugin#12]
I'm trying to use this plugin with DFP and we often have wrappers. Can you please add support for wrappers?

**Comment by saketsoni** [comment]
Hello,

Regarding this reply
_"The issue here (if you look at the network requests) is that the test player is requesting the VAST file twice, and DFP does this really fun thing where subsequent requests with the same "correlator" value lead to an empty file. So, on the second request, DFP returns an empty file, the player says "ok, well then I guess I'll just play the video"."_

Please let me know if there is a solution to this.

According to this page: https://support.google.com/dfp_premium/answer/1068325?hl=en
_"**A random number, typically the timestamp of the page view, that's shared by multiple requests coming from the same page view.** If you're not using the Google IMA SDK, see note below.\* Correlator is used to implement competitive exclusions, including in cookieless environments."_

Thank you
